apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartsheet-picklist-updater
  namespace: internal-tooling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartsheet-picklist-updater
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'smartsheet-picklist-updater'
        vault.hashicorp.com/agent-inject-secret-picklistupdater: 'secret/picklistupdater'
        vault.hashicorp.com/agent-inject-template-picklistupdater: |
          {{- with secret "secret/picklistupdater" -}}
            export SHARED_SECRET="{{ .Data.data.sharedsecret }}"
            export CONTRACT_SHARED_SECRET="{{ .Data.data.contractsharedsecret }}"
            export SMARTSHEET_API_TOKEN="{{ .Data.data.smartsheettoken }}"
            export SMARTSHEET_TIME_TRACKING_FOLDER_ID="{{ .Data.data.folderids }}"
            export MASTER_CUST_LIST_SHEET_ID="{{ .Data.data.masterid }}"
            export MASTER_SHEET_NAME="{{ .Data.data.mastername }}"
            export MASTER_CONTRACT_LIST_SHEET_ID="{{ .Data.data.contractid }}"
            export CONTRACT_TRACKING_FOLDER_ID="{{ .Data.data.contractfolderid }}"
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/ca-cert: /run/secrets/kubernetes.io/serviceaccount/ca.crt
      labels:
        app: smartsheet-picklist-updater
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10014
        runAsGroup: 10015
      containers:
        - image: harbor.pscp-css.support/library/smartsheet-picklist-updater:0.0.24
          name: smartsheet-picklist-updater
          command: ['sh', '-c', 'source /vault/secrets/picklistupdater && python -m uvicorn smartsheet_picklist_updater:app --host 0.0.0.0 --port 8000 --root-path /picklistupdater']
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: smartsheet-picklist-updater
